### ISSUE TITLE
Issue running or starting mifosx 

### ISSUE THREAD

**Issue by iaubain** [openMF/mifosx#1639]
Hello, Mifosx team,
I am new to MIFOS and I wanted to run it locally on my computer and I did like instructed on this link:
[https://mifosforge.jira.com/wiki/spaces/MDZ/pages/93093944/IntelliJ+IDEA+Setup](url), Note that I am using intellij idea. When I try to run the ServerApplication (because I have already installed Mysql), or ServerWithMariaDB4jApplication which is an other alternative offered. I am getting an unexpected Error:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/catalina/connector/Connector
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:140)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:273)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:219)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:440)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:259)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:219)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:186)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:156)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:305)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:611)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:952)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:941)
	at org.apache.fineract.ServerApplication.main(ServerApplication.java:52)
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.connector.Connector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more

Process finished with exit code 1

Any help will be appreciated.
Kind regards

**Comment by vorburger** [comment]
@iaubain thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz
